"""initial schema

Revision ID: ed158b3379d5
Revises: 
Create Date: 2026-07-28 00:02:55.179731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed158b3379d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obligations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('requires_document', sa.Boolean(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=True),
    sa.Column('company_tax_id', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'submitted', 'done')", name='ck_obligations_status_valid'),
    sa.CheckConstraint("type IN ('annual_report', 'franchise_tax', 'boi_report', 'registered_agent_renewal')", name='ck_obligations_type_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('obligation_id', sa.Uuid(), nullable=False),
    sa.Column('previous_status', sa.String(length=16), nullable=False),
    sa.Column('new_status', sa.String(length=16), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_entries')
    op.drop_table('obligations')
    # ### end Alembic commands ###
